services:
  rustapp:
    container_name: rust-backend
    image: maxthemerman/rust-backend:latest
    build:
      context: ./backend
      dockerfile: rust.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: p
      POSTGRES_DB: work
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}